enum friendErrors {
  INVALID_RELATIONSHIP,
  USER_NOT_FOUND,
  FRIENDSHIP_EXISTED,
  INVALID_OPERATION_ON_STRANGER,
  CANNOT_PERFORM_ON_SELF,
  FAILED_TO_FETCH_FRIENDS,
  SUCCESS,
};

export { friendErrors };